# Generated by Django 5.0.6 on 2024-05-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeinfo',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='completeinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
