# Generated by Django 5.0.6 on 2024-05-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_completeinfo_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='athlete',
            name='practices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
