# Generated by Django 5.0.6 on 2024-05-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_athlete_birth_date_athlete_practices'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
